# This is a basic workflow to help you get started with Actions

name: Gatling CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
  
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      
      - name: Run gatling tests with Maven
        run: mvn gatling:test -Dgatling.simulationClass=simulations.ReqResEndToEndTests -DUsers=20 -DRAMP_DURATION=10 -DDURATION=30
